CREATE SEQUENCE SEQ_CLIENTES AS INTEGER START WITH 1
  INCREMENT BY 1;

CREATE TABLE CLIENTES (CLIENTE_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
CLIENTE_NOMBRE VARCHAR(50) NOT NULL,
CLIENTE_APELLIDO VARCHAR(50) NOT NULL,
CLIENTE_EDAD INTEGER NOT NULL,
CLIENTE_FECHA_NACIMIENTO DATE NOT NULL);

INSERT INTO CLIENTES (CLIENTE_NOMBRE, CLIENTE_APELLIDO, CLIENTE_EDAD, CLIENTE_FECHA_NACIMIENTO) 
VALUES ('Jhon', 'Doe', 45, '1978-12-10');